/**
 * 
 */
package fr.iessa.controleur;

/**
 * @author hodiqual
 *
 */
public enum ModeleEvent {
	
	CHARGEMENT_CARTE_FICHIER_DONE
,	CHARGEMENT_CARTE_FICHIER_ERREUR
,   CHARGEMENT_CARTE_FICHIER_EN_COURS

,	CHARGEMENT_TRAFIC_FICHIER_DONE
,	CHARGEMENT_TRAFIC_FICHIER_ERREUR
,   CHARGEMENT_TRAFIC_FICHIER_EN_COURS

,   UPDATE_INSTANT
,   UPDATE_IS_TRAFIC_RUNNING
,	UPDATE_DUREE_INTERVALLE

, 	UPDATE_FILTRE_VOL

,   SAUVEGARDE_COLLISION_ERREUR
,   SAUVEGARDE_COLLISION_DONE

,	SHOW_COLLISION
,	HIDE_COLLISION
;
}
